# Stock Analysis

In [1]:
import yfinance as yf
import json
import requests
from bs4 import BeautifulSoup
from selenium import webdriver
import string

### Download market data
First we need to download all the stock tickers. 
TODO: Identify what are all the tickers

In [2]:
allTickers = []

for alphabet in string.ascii_lowercase:
    page = requests.get(f"http://eoddata.com/stocklist/NASDAQ/{alphabet}.htm")
    contents = page.content
    soup = BeautifulSoup(contents, 'html.parser')
    rows = soup.find("div", {"id": "ctl00_cph1_divSymbols"}).find_all("tr", {"class": ["ro", "re"]})
    tickers = [row.find("a").text for row in rows]
    allTickers.extend(tickers)

In [3]:
len(allTickers)

3572

In [4]:
print(allTickers)

['AACG', 'AAL', 'AAME', 'AAOI', 'AAON', 'AAPL', 'AAWW', 'AAXJ', 'AAXN', 'ABCB', 'ABEO', 'ABIO', 'ABMD', 'ABTX', 'ABUS', 'ACAD', 'ACAM', 'ACAMU', 'ACAMW', 'ACBI', 'ACER', 'ACGL', 'ACGLO', 'ACGLP', 'ACHC', 'ACHV', 'ACIA', 'ACIU', 'ACIW', 'ACLS', 'ACMR', 'ACNB', 'ACOR', 'ACRS', 'ACRX', 'ACST', 'ACT', 'ACTG', 'ACTT', 'ACTTU', 'ACTTW', 'ACWI', 'ACWX', 'ADAP', 'ADBE', 'ADES', 'ADI', 'ADIL', 'ADILW', 'ADMA', 'ADMP', 'ADMS', 'ADP', 'ADPT', 'ADRA', 'ADRD', 'ADRE', 'ADRO', 'ADRU', 'ADSK', 'ADTN', 'ADUS', 'ADVM', 'ADXN', 'ADXS', 'AEGN', 'AEHR', 'AEIS', 'AEMD', 'AERI', 'AESE', 'AEY', 'AEYE', 'AEZS', 'AFH', 'AFIN', 'AFINP', 'AFMD', 'AFYA', 'AGBA', 'AGBAR', 'AGBAU', 'AGBAW', 'AGEN', 'AGFS', 'AGFSW', 'AGIO', 'AGLE', 'AGMH', 'AGNC', 'AGNCM', 'AGNCN', 'AGNCO', 'AGNCP', 'AGND', 'AGRX', 'AGTC', 'AGYS', 'AGZD', 'AHCO', 'AHPI', 'AIA', 'AIH', 'AIHS', 'AIMC', 'AIMT', 'AINV', 'AIQ', 'AIRG', 'AIRR', 'AIRT', 'AIRTP', 'AIRTW', 'AKAM', 'AKBA', 'AKCA', 'AKER', 'AKRO', 'AKRX', 'AKTS', 'AKTX', 'ALAC', 'ALACR', 'ALACW', 'ALBO', 'ALCO', 'ALDX', 'ALEC', 'ALGN', 'ALGR', 'ALGRR', 'ALGRW', 'ALGT', 'ALIM', 'ALJJ', 'ALKS', 'ALLK', 'ALLO', 'ALLT', 'ALNA', 'ALNY', 'ALOT', 'ALPN', 'ALRM', 'ALRN', 'ALRS', 'ALSK', 'ALT', 'ALTM', 'ALTR', 'ALTY', 'ALXN', 'ALYA', 'AMAG', 'AMAL', 'AMAT', 'AMBA', 'AMCA', 'AMCI', 'AMCIU', 'AMCIW', 'AMCX', 'AMD', 'AMED', 'AMEH', 'AMGN', 'AMHC', 'AMHCU', 'AMHCW', 'AMKR', 'AMNB', 'AMOT', 'AMPH', 'AMRB', 'AMRH', 'AMRHW', 'AMRK', 'AMRN', 'AMRS', 'AMSC', 'AMSF', 'AMSWA', 'AMTB', 'AMTBB', 'AMTD', 'AMTX', 'AMWD', 'AMZN', 'ANAB', 'ANAT', 'ANCN', 'ANDA', 'ANDAR', 'ANDAU', 'ANDAW', 'ANDE', 'ANGI', 'ANGL', 'ANGO', 'ANIK', 'ANIP', 'ANIX', 'ANPC', 'ANSS', 'ANTE', 'ANY', 'AOBC', 'AOSL', 'APDN', 'APEI', 'APEN', 'APEX', 'APLS', 'APLT', 'APM', 'APOG', 'APOP', 'APOPW', 'APPF', 'APPN', 'APPS', 'APRE', 'APTO', 'APTX', 'APVO', 'APWC', 'APXT', 'APXTU', 'APXTW', 'APYX', 'AQB', 'AQMS', 'AQST', 'ARAV', 'ARAY', 'ARCB', 'ARCC', 'ARCE', 'ARCT', 'ARDS', 'ARDX', 'AREC', 'ARGX', 'ARKR', 'ARLP', 'ARNA', 'AROW', 'ARPO', 'ARQT', 'ARTL', 'ARTLW', 'ARTNA', 'ARTW', 'ARVN', 'ARWR', 'ARYA', 'ARYAU', 'ARYAW', 'ASET', 'ASFI', 'ASLN', 'ASMB', 'ASML', 'ASNA', 'ASND', 'ASPS', 'ASPU', 'ASRT', 'ASRV', 'ASRVP', 'ASTC', 'ASTE', 'ASUR', 'ASYS', 'ATAX', 'ATCX', 'ATCXW', 'ATEC', 'ATEX', 'ATHE', 'ATHX', 'ATIF', 'ATLC', 'ATLO', 'ATNI', 'ATNX', 'ATOM', 'ATOS', 'ATRA', 'ATRC', 'ATRI', 'ATRO', 'ATRS', 'ATSG', 'ATVI', 'ATXI', 'AUB', 'AUBN', 'AUDC', 'AUPH', 'AUTL', 'AUTO', 'AVAV', 'AVCO', 'AVDL', 'AVEO', 'AVGO', 'AVGOP', 'AVGR', 'AVID', 'AVNW', 'AVRO', 'AVT', 'AVXL', 'AWRE', 'AXAS', 'AXDX', 'AXGN', 'AXGT', 'AXLA', 'AXNX', 'AXSM', 'AXTI', 'AY', 'AYTU', 'AZPN', 'AZRX', 'BAND', 'BANF', 'BANFP', 'BANR', 'BANX', 'BASI', 'BATRA', 'BATRK', 'BBBY', 'BBCP', 'BBGI', 'BBH', 'BBI', 'BBIO', 'BBQ', 'BBSI', 'BCBP', 'BCDA', 'BCDAW', 'BCEL', 'BCLI', 'BCML', 'BCOM', 'BCOR', 'BCOV', 'BCOW', 'BCPC', 'BCRX', 'BCTF', 'BCYC', 'BDGE', 'BDSI', 'BDTX', 'BEAM', 'BEAT', 'BECN', 'BELFA', 'BELFB', 'BFC', 'BFIN', 'BFIT', 'BFRA', 'BFST', 'BFYT', 'BGCP', 'BGFV', 'BGNE', 'BGRN', 'BHAT', 'BHF', 'BHFAL', 'BHFAP', 'BHTG', 'BIB', 'BICK', 'BIDU', 'BIIB', 'BILI', 'BIMI', 'BIOC', 'BIOL', 'BIS', 'BJK', 'BJRI', 'BKCC', 'BKEP', 'BKEPP', 'BKNG', 'BKSC', 'BKYI', 'BL', 'BLBD', 'BLCM', 'BLCN', 'BLDP', 'BLDR', 'BLFS', 'BLIN', 'BLKB', 'BLMN', 'BLNK', 'BLNKW', 'BLPH', 'BLRX', 'BLU', 'BLUE', 'BMCH', 'BMLP', 'BMRA', 'BMRC', 'BMRN', 'BMTC', 'BND', 'BNDW', 'BNDX', 'BNFT', 'BNGO', 'BNGOW', 'BNSO', 'BNTC', 'BNTCW', 'BNTX', 'BOCH', 'BOKF', 'BOKFL', 'BOMN', 'BOOM', 'BOSC', 'BOTJ', 'BOTZ', 'BOXL', 'BPFH', 'BPMC', 'BPOP', 'BPOPM', 'BPOPN', 'BPR', 'BPRAP', 'BPRN', 'BPTH', 'BPY', 'BPYPN', 'BPYPO', 'BPYPP', 'BPYU', 'BPYUP', 'BREW', 'BRID', 'BRKL', 'BRKR', 'BRKS', 'BROG', 'BROGW', 'BRP', 'BRPA', 'BRPAR', 'BRPAU', 'BRPAW', 'BRQS', 'BRY', 'BSAE', 'BSBE', 'BSBK', 'BSCE', 'BSCK', 'BSCL', 'BSCM', 'BSCN', 'BSCO', 'BSCP', 'BSCQ', 'BSCR', 'BSCS', 'BSCT', 'BSDE', 'BSET', 'BSGM', 'BSJK', 'BSJL', 'BSJM', 'BSJN', 'BSJO', 'BSJP', 'BSJQ', 'BSJR', 'BSML', 'BSMM', 'BSMN', 'BSMO', 'BSMP', 'BSMQ', 'BSMR', 'BSMS', 'BSMT', 'BSQR', 'BSRR', 'BSTC', 'BSVN', 'BTAI', 'BTEC', 'BUG', 'BURG', 'BUSE', 'BVSN', 'BVXV', 'BVXVW', 'BWAY', 'BWB', 'BWEN', 'BWFG', 'BWMC', 'BWMCW', 'BXRX', 'BYFC', 'BYND', 'BYSI', 'BZUN', 'CAAS', 'CABA', 'CAC', 'CACC', 'CACG', 'CAKE', 'CALA', 'CALM', 'CAMP', 'CAMT', 'CAN', 'CAPR', 'CAR', 'CARA', 'CARE', 'CARG', 'CARO', 'CARV', 'CARZ', 'CASA', 'CASH', 'CASI', 'CASS', 'CASY', 'CATB', 'CATC', 'CATH', 'CATM', 'CATS', 'CATY', 'CBAN', 'CBAT', 'CBAY', 'CBFV', 'CBIO', 'CBLI', 'CBMB', 'CBMG', 'CBNK', 'CBPO', 'CBRL', 'CBSH', 'CBSHP', 'CBTX', 'CCAP', 'CCB', 'CCBG', 'CCCL', 'CCD', 'CCLP', 'CCMP', 'CCNE', 'CCOI', 'CCRC', 'CCRN', 'CCXI', 'CDC', 'CDEV', 'CDK', 'CDL', 'CDLX', 'CDMO', 'CDMOP', 'CDNA', 'CDNS', 'CDTX', 'CDW', 'CDXC', 'CDXS', 'CDZI', 'CECE', 'CELC', 'CELH', 'CEMI', 'CENT', 'CENTA', 'CENX', 'CERC', 'CERN', 'CERS', 'CETV', 'CETX', 'CETXP', 'CETXW', 'CEVA', 'CEY', 'CEZ', 'CFA', 'CFB', 'CFBI', 'CFBK', 'CFFA', 'CFFAU', 'CFFAW', 'CFFI', 'CFFN', 'CFMS', 'CFO', 'CFRX', 'CG', 'CGBD', 'CGEN', 'CGIX', 'CGNX', 'CGO', 'CHCI', 'CHCO', 'CHDN', 'CHEF', 'CHEK', 'CHEKW', 'CHEKZ', 'CHFS', 'CHI', 'CHKP', 'CHMA', 'CHMG', 'CHNA', 'CHNG', 'CHNGU', 'CHNGV', 'CHNR', 'CHPM', 'CHPMU', 'CHPMW', 'CHRS', 'CHRW', 'CHSCL', 'CHSCM', 'CHSCN', 'CHSCO', 'CHSCP', 'CHTR', 'CHUY', 'CHW', 'CHY', 'CIBR', 'CID', 'CIDM', 'CIFS', 'CIGI', 'CIH', 'CIIC', 'CIICU', 'CIICW', 'CIL', 'CINF', 'CIVB', 'CIZ', 'CIZN', 'CJJD', 'CKPT', 'CLAR', 'CLBK', 'CLBS', 'CLCT', 'CLDB', 'CLDX', 'CLFD', 'CLGN', 'CLIR', 'CLLS', 'CLMT', 'CLNE', 'CLOU', 'CLPS', 'CLPT', 'CLRB', 'CLRBZ', 'CLRG', 'CLRO', 'CLSD', 'CLSK', 'CLSN', 'CLUB', 'CLVS', 'CLWT', 'CLXT', 'CMBM', 'CMCO', 'CMCSA', 'CMCT', 'CMCTP', 'CME', 'CMFNL', 'CMLS', 'CMPR', 'CMRX', 'CMTL', 'CNAT', 'CNBKA', 'CNCE', 'CNCR', 'CNDT', 'CNET', 'CNFR', 'CNFRL', 'CNNB', 'CNOB', 'CNSL', 'CNSP', 'CNST', 'CNTG', 'CNTY', 'CNXN', 'COCP', 'CODA', 'CODX', 'COFS', 'COHR', 'COHU', 'COKE', 'COLB', 'COLL', 'COLM', 'COMM', 'COMT', 'CONE', 'CONN', 'COOP', 'CORE', 'CORT', 'CORV', 'COST', 'COUP', 'COWN', 'COWNL', 'COWNZ', 'CPAA', 'CPAAU', 'CPAAW', 'CPAH', 'CPHC', 'CPIX', 'CPLP', 'CPRT', 'CPRX', 'CPSH', 'CPSI', 'CPSS', 'CPST', 'CPTA', 'CPTAG', 'CPTAL', 'CPZ', 'CRAI', 'CRBP', 'CREE', 'CREG', 'CRESY', 'CREX', 'CRIS', 'CRMT', 'CRNC', 'CRNT', 'CRNX', 'CRON', 'CROX', 'CRSA', 'CRSAU', 'CRSAW', 'CRSP', 'CRTO', 'CRTX', 'CRUS', 'CRVL', 'CRVS', 'CRWD', 'CRWS', 'CSA', 'CSB', 'CSBR', 'CSCO', 'CSF', 'CSFL', 'CSGP', 'CSGS', 'CSII', 'CSIQ', 'CSML', 'CSOD', 'CSPI', 'CSQ', 'CSSE', 'CSSEP', 'CSTE', 'CSTL', 'CSTR', 'CSWC', 'CSWCL', 'CSWI', 'CSX', 'CTAC', 'CTACU', 'CTACW', 'CTAS', 'CTBI', 'CTG', 'CTHR', 'CTIB', 'CTIC', 'CTMX', 'CTRC', 'CTRE', 'CTRM', 'CTRN', 'CTSH', 'CTSO', 'CTXR', 'CTXRW', 'CTXS', 'CUBA', 'CUE', 'CUI', 'CUTR', 'CVBF', 'CVCO', 'CVCY', 'CVET', 'CVGI', 'CVGW', 'CVLT', 'CVLY', 'CVTI', 'CVV', 'CWBC', 'CWBR', 'CWCO', 'CWST', 'CXDC', 'CXSE', 'CY', 'CYAD', 'CYAN', 'CYBE', 'CYBR', 'CYCC', 'CYCCP', 'CYCN', 'CYOU', 'CYRN', 'CYRX', 'CYRXW', 'CYTK', 'CZNC', 'CZR', 'CZWI', 'DAIO', 'DAKT', 'DALI', 'DARE', 'DAX', 'DBVT', 'DBX', 'DCAR', 'DCIX', 'DCOM', 'DCOMP', 'DCPH', 'DDIV', 'DDMX', 'DDMXW', 'DDOG', 'DEAC', 'DEACU', 'DEACW', 'DENN', 'DERM', 'DFFN', 'DFNL', 'DFNSU', 'DGICA', 'DGICB', 'DGII', 'DGLD', 'DGLY', 'DGRE', 'DGRS', 'DGRW', 'DHC', 'DHCNI', 'DHCNL', 'DHIL', 'DINT', 'DIOD', 'DISCA', 'DISCB', 'DISCK', 'DISH', 'DJCO', 'DLHC', 'DLPN', 'DLPNW', 'DLTH', 'DLTR', 'DMAC', 'DMLP', 'DMPI', 'DMRC', 'DMTK', 'DNKN', 'DNLI', 'DOCU', 'DOGZ', 'DOMO', 'DOOO', 'DORM', 'DOX', 'DOYU', 'DPHC', 'DPHCU', 'DPHCW', 'DRAD', 'DRADP', 'DRIO', 'DRIOW', 'DRIV', 'DRNA', 'DRRX', 'DRTT', 'DSGX', 'DSKE', 'DSKEW', 'DSLV', 'DSPG', 'DSWL', 'DTEA', 'DTIL', 'DTSS', 'DUO', 'DUOT', 'DUSA', 'DVAX', 'DVLU', 'DVOL', 'DVY', 'DWAQ', 'DWAS', 'DWAT', 'DWAW', 'DWCR', 'DWEQ', 'DWFI', 'DWIN', 'DWLD', 'DWMC', 'DWPP', 'DWSH', 'DWSN', 'DWTR', 'DWUS', 'DXCM', 'DXGE', 'DXJS', 'DXLG', 'DXPE', 'DXYN', 'DYAI', 'DYNT', 'DZSI', 'EA', 'EARS', 'EAST', 'EBAY', 'EBAYL', 'EBIX', 'EBIZ', 'EBMT', 'EBSB', 'EBTC', 'ECHO', 'ECOL', 'ECOLW', 'ECOR', 'ECOW', 'ECPG', 'EDAP', 'EDIT', 'EDNT', 'EDRY', 'EDSA', 'EDTX', 'EDTXU', 'EDTXW', 'EDUC', 'EEFT', 'EEMA', 'EFAS', 'EFOI', 'EFSC', 'EGAN', 'EGBN', 'EGLE', 'EGOV', 'EGRX', 'EH', 'EHTH', 'EIDX', 'EIGI', 'EIGR', 'EKSO', 'ELGX', 'ELOX', 'ELSE', 'ELTK', 'EMB', 'EMCB', 'EMCF', 'EMCG', 'EMIF', 'EMKR', 'EML', 'EMMS', 'EMXC', 'ENDP', 'ENG', 'ENLV', 'ENOB', 'ENPH', 'ENSG', 'ENT', 'ENTA', 'ENTG', 'ENTX', 'ENTXW', 'ENZL', 'EOLS', 'EPAY', 'EPIX', 'EPSN', 'EPZM', 'EQ', 'EQBK', 'EQIX', 'EQRR', 'ERI', 'ERIC', 'ERIE', 'ERII', 'ERYP', 'ESBK', 'ESCA', 'ESEA', 'ESGD', 'ESGE', 'ESGR', 'ESGRO', 'ESGRP', 'ESGU', 'ESLT', 'ESPO', 'ESPR', 'ESQ', 'ESSA', 'ESSCU', 'ESTA', 'ESXB', 'ETFC', 'ETNB', 'ETON', 'ETSY', 'ETTX', 'EUFN', 'EVBG', 'EVER', 'EVFM', 'EVGBC', 'EVGN', 'EVK', 'EVLO', 'EVOK', 'EVOL', 'EVOP', 'EVSI', 'EVSIW', 'EWBC', 'EWJE', 'EWJV', 'EWZS', 'EXAS', 'EXC', 'EXEL', 'EXFO', 'EXLS', 'EXPC', 'EXPCU', 'EXPCW', 'EXPD', 'EXPE', 'EXPI', 'EXPO', 'EXTR', 'EYE', 'EYEG', 'EYEGW', 'EYEN', 'EYES', 'EYESW', 'EYPT', 'EZPW', 'FAAR', 'FAB', 'FAD', 'FALN', 'FAMI', 'FANG', 'FANH', 'FARM', 'FARO', 'FAST', 'FAT', 'FATE', 'FB', 'FBIO', 'FBIOP', 'FBIZ', 'FBMS', 'FBNC', 'FBSS', 'FBZ', 'FCA', 'FCAL', 'FCAN', 'FCAP', 'FCBC', 'FCBP', 'FCCO', 'FCCY', 'FCEF', 'FCEL', 'FCFS', 'FCNCA', 'FCVT', 'FDBC', 'FDEF', 'FDIV', 'FDNI', 'FDT', 'FDTS', 'FDUS', 'FDUSG', 'FDUSL', 'FDUSZ', 'FEIM', 'FELE', 'FEM', 'FEMB', 'FEMS', 'FENC', 'FEP', 'FEUZ', 'FEX', 'FEYE', 'FFBC', 'FFBW', 'FFHL', 'FFIC', 'FFIN', 'FFIV', 'FFNW', 'FFWM', 'FGBI', 'FGEN', 'FGM', 'FHB', 'FHK', 'FIBK', 'FID', 'FINX', 'FISI', 'FISV', 'FITB', 'FITBI', 'FITBO', 'FITBP', 'FIVE', 'FIVN', 'FIXD', 'FIXX', 'FIZZ', 'FJP', 'FKO', 'FKU', 'FLDM', 'FLEX', 'FLGT', 'FLIC', 'FLIR', 'FLL', 'FLLC', 'FLLCR', 'FLLCU', 'FLLCW', 'FLMN', 'FLMNW', 'FLN', 'FLNT', 'FLWS', 'FLXN', 'FLXS', 'FMAO', 'FMB', 'FMBH', 'FMBI', 'FMCI', 'FMCIU', 'FMCIW', 'FMHI', 'FMK', 'FMNB', 'FNCB', 'FNHC', 'FNJN', 'FNK', 'FNKO', 'FNLC', 'FNWB', 'FNX', 'FNY', 'FOCS', 'FOLD', 'FOMX', 'FONR', 'FORD', 'FORK', 'FORM', 'FORR', 'FORTY', 'FOSL', 'FOX', 'FOXA', 'FOXF', 'FPA', 'FPAY', 'FPAYW', 'FPRX', 'FPXE', 'FPXI', 'FRAF', 'FRAN', 'FRBA', 'FRBK', 'FREQ', 'FRG', 'FRGI', 'FRHC', 'FRME', 'FRPH', 'FRPT', 'FRSX', 'FRTA', 'FSBC', 'FSBW', 'FSCT', 'FSEA', 'FSFG', 'FSLR', 'FSRV', 'FSRVU', 'FSRVW', 'FSTR', 'FSV', 'FSZ', 'FTA', 'FTAC', 'FTACU', 'FTACW', 'FTAG', 'FTC', 'FTCS', 'FTDR', 'FTEK', 'FTFT', 'FTGC', 'FTHI', 'FTLB', 'FTNT', 'FTR', 'FTRI', 'FTSL', 'FTSM', 'FTSV', 'FTXD', 'FTXG', 'FTXH', 'FTXL', 'FTXN', 'FTXO', 'FTXR', 'FULC', 'FULT', 'FUNC', 'FUND', 'FUSB', 'FUTU', 'FUV', 'FV', 'FVC', 'FVCB', 'FVE', 'FWONA', 'FWONK', 'FWP', 'FWRD', 'FXNC', 'FYC', 'FYT', 'FYX', 'GABC', 'GAIA', 'GAIN', 'GAINL', 'GAINM', 'GALT', 'GARS', 'GASS', 'GBCI', 'GBDC', 'GBLI', 'GBLIL', 'GBLIZ', 'GBT', 'GCBC', 'GCVRZ', 'GDEN', 'GDS', 'GDYN', 'GDYNW', 'GEC', 'GECC', 'GECCL', 'GECCM', 'GECCN', 'GENC', 'GENE', 'GENY', 'GEOS', 'GERN', 'GEVO', 'GFED', 'GFN', 'GFNCP', 'GFNSL', 'GGAL', 'GH', 'GHIVU', 'GHSI', 'GIFI', 'GIGE', 'GIGM', 'GIII', 'GILD', 'GILT', 'GLAD', 'GLADD', 'GLADL', 'GLBS', 'GLBZ', 'GLDD', 'GLDI', 'GLG', 'GLIBA', 'GLIBP', 'GLMD', 'GLNG', 'GLPG', 'GLPI', 'GLRE', 'GLUU', 'GLYC', 'GMAB', 'GMDA', 'GMHI', 'GMHIU', 'GMHIW', 'GMLP', 'GMLPP', 'GNCA', 'GNFT', 'GNLN', 'GNMA', 'GNMK', 'GNOM', 'GNPX', 'GNRSU', 'GNSS', 'GNTX', 'GNTY', 'GNUS', 'GO', 'GOGL', 'GOGO', 'GOOD', 'GOODM', 'GOODN', 'GOOG', 'GOOGL', 'GOSS', 'GPAQ', 'GPAQW', 'GPOR', 'GPP', 'GPRE', 'GPRO', 'GRBK', 'GRFS', 'GRID', 'GRIF', 'GRIL', 'GRIN', 'GRMN', 'GRNQ', 'GRNV', 'GRNVR', 'GRNVU', 'GRNVW', 'GROW', 'GRPN', 'GRTS', 'GRTX', 'GRVY', 'GRWG', 'GSBC', 'GSHD', 'GSIT', 'GSKY', 'GSM', 'GSMG', 'GSMGW', 'GSUM', 'GT', 'GTEC', 'GTHX', 'GTIM', 'GTLS', 'GTYH', 'GULF', 'GURE', 'GVP', 'GWGH', 'GWPH', 'GWRS', 'GXGX', 'GXGXU', 'GXGXW', 'GXTG', 'GYRO', 'HA', 'HABT', 'HAFC', 'HAIN', 'HALL', 'HALO', 'HAPP', 'HARP', 'HAS', 'HAYN', 'HBAN', 'HBANN', 'HBANO', 'HBCP', 'HBIO', 'HBMD', 'HBNC', 'HBP', 'HBT', 'HCAC', 'HCACU', 'HCACW', 'HCAP', 'HCAPZ', 'HCAT', 'HCCH', 'HCCHR', 'HCCHU', 'HCCHW', 'HCCI', 'HCCO', 'HCCOU', 'HCCOW', 'HCKT', 'HCM', 'HCSG', 'HDS', 'HDSN', 'HEAR', 'HEBT', 'HEES', 'HELE', 'HEPA', 'HERD', 'HERO', 'HEWG', 'HFBL', 'HFFG', 'HFWA', 'HGSH', 'HHHH', 'HHHHR', 'HHHHU', 'HHHHW', 'HHR', 'HHT', 'HIBB', 'HIFS', 'HIHO', 'HIIQ', 'HIMX', 'HJLI', 'HJLIW', 'HLAL', 'HLG', 'HLIO', 'HLIT', 'HLNE', 'HMHC', 'HMNF', 'HMST', 'HMSY', 'HMTV', 'HNDL', 'HNNA', 'HNRG', 'HOFT', 'HOLI', 'HOLX', 'HOMB', 'HONE', 'HOOK', 'HOPE', 'HOTH', 'HOVNP', 'HQI', 'HQY', 'HROW', 'HRTX', 'HRZN', 'HSDT', 'HSIC', 'HSII', 'HSKA', 'HSON', 'HSTM', 'HTBI', 'HTBK', 'HTBX', 'HTGM', 'HTHT', 'HTIA', 'HTLD', 'HTLF', 'HUBG', 'HUGE', 'HUIZ', 'HURC', 'HURN', 'HVBC', 'HWBK', 'HWC', 'HWCC', 'HWCPL', 'HWKN', 'HX', 'HYAC', 'HYACU', 'HYACW', 'HYLS', 'HYND', 'HYRE', 'HYXE', 'HYZD', 'HZNP', 'IAC', 'IART', 'IBB', 'IBCP', 'IBKC', 'IBKCN', 'IBKCO', 'IBKCP', 'IBKR', 'IBOC', 'IBTA', 'IBTB', 'IBTD', 'IBTE', 'IBTF', 'IBTG', 'IBTH', 'IBTI', 'IBTJ', 'IBTX', 'IBUY', 'ICAD', 'ICBK', 'ICCC', 'ICCH', 'ICFI', 'ICHR', 'ICLK', 'ICLN', 'ICLR', 'ICMB', 'ICON', 'ICPT', 'ICUI', 'IDCC', 'IDEX', 'IDLB', 'IDN', 'IDRA', 'IDXG', 'IDXX', 'IDYA', 'IEA', 'IEAWW', 'IEC', 'IEF', 'IEI', 'IEP', 'IESC', 'IEUS', 'IFEU', 'IFGL', 'IFMK', 'IFRX', 'IFV', 'IGF', 'IGIB', 'IGMS', 'IGOV', 'IGSB', 'IHRT', 'III', 'IIIN', 'IIIV', 'IIN', 'IIVI', 'IJT', 'IKNX', 'ILMN', 'ILPT', 'IMAB', 'IMAC', 'IMACW', 'IMBI', 'IMGN', 'IMKTA', 'IMMP', 'IMMR', 'IMMU', 'IMOS', 'IMRN', 'IMRNW', 'IMTE', 'IMUX', 'IMV', 'IMVT', 'IMVTU', 'IMVTW', 'IMXI', 'INAP', 'INBK', 'INBKL', 'INBKZ', 'INCY', 'INDB', 'INDY', 'INFI', 'INFN', 'INFR', 'INGN', 'INMB', 'INMD', 'INNT', 'INO', 'INOD', 'INOV', 'INPX', 'INSE', 'INSG', 'INSM', 'INSU', 'INSUU', 'INSUW', 'INTC', 'INTG', 'INTL', 'INTU', 'INVA', 'INVE', 'INWK', 'IONS', 'IOSP', 'IOTS', 'IOVA', 'IPAR', 'IPGP', 'IPHA', 'IPKW', 'IPLDP', 'IPWR', 'IQ', 'IRBT', 'IRCP', 'IRDM', 'IRIX', 'IRMD', 'IROQ', 'IRTC', 'IRWD', 'ISBC', 'ISDS', 'ISDX', 'ISEE', 'ISEM', 'ISHG', 'ISIG', 'ISNS', 'ISRG', 'ISSC', 'ISTB', 'ISTR', 'ITCI', 'ITI', 'ITIC', 'ITMR', 'ITRI', 'ITRM', 'ITRN', 'IUS', 'IUSB', 'IUSG', 'IUSS', 'IUSV', 'IVAC', 'IXUS', 'IZEA', 'JACK', 'JAGX', 'JAKK', 'JAN', 'JAZZ', 'JBHT', 'JBLU', 'JBSS', 'JCOM', 'JCS', 'JCTCF', 'JD', 'JFIN', 'JFK', 'JFKKR', 'JFKKU', 'JFKKW', 'JFU', 'JG', 'JJSF', 'JKHY', 'JKI', 'JMPNL', 'JMPNZ', 'JNCE', 'JOBS', 'JOUT', 'JRJC', 'JRSH', 'JRVR', 'JSM', 'JSMD', 'JSML', 'JVA', 'JYNT', 'KALA', 'KALU', 'KALV', 'KBAL', 'KBLM', 'KBLMR', 'KBLMW', 'KBSF', 'KBWB', 'KBWD', 'KBWP', 'KBWR', 'KBWY', 'KCAPL', 'KE', 'KELYA', 'KELYB', 'KEQU', 'KERN', 'KERNW', 'KFFB', 'KFRC', 'KGJI', 'KHC', 'KIDS', 'KIN', 'KINS', 'KIRK', 'KLAC', 'KLDO', 'KLIC', 'KLXE', 'KMDA', 'KMPH', 'KNDI', 'KNSA', 'KNSL', 'KOD', 'KOPN', 'KOSS', 'KPTI', 'KRKR', 'KRMA', 'KRMD', 'KRNT', 'KRNY', 'KRTX', 'KRUS', 'KRYS', 'KTCC', 'KTOS', 'KTOV', 'KTOVW', 'KURA', 'KVHI', 'KXIN', 'KZIA', 'KZR', 'LACQ', 'LACQU', 'LACQW', 'LAKE', 'LAMR', 'LANC', 'LAND', 'LANDP', 'LARK', 'LASR', 'LATN', 'LATNU', 'LATNW', 'LAUR', 'LAWS', 'LAZY', 'LBAI', 'LBC', 'LBRDA', 'LBRDK', 'LBTYA', 'LBTYB', 'LBTYK', 'LCA', 'LCAHU', 'LCAHW', 'LCNB', 'LCUT', 'LDEM', 'LDRI', 'LDSF', 'LE', 'LECO', 'LEDS', 'LEGH', 'LEGR', 'LEVL', 'LFAC', 'LFACU', 'LFACW', 'LFUS', 'LFVN', 'LGIH', 'LGND', 'LHCG', 'LIFE', 'LILA', 'LILAK', 'LINC', 'LIND', 'LIQT', 'LITE', 'LIVE', 'LIVK', 'LIVKU', 'LIVKW', 'LIVN', 'LIVX', 'LIZI', 'LJPC', 'LK', 'LKCO', 'LKFN', 'LKQ', 'LLIT', 'LLNW', 'LMAT', 'LMB', 'LMBS', 'LMFA', 'LMFAW', 'LMNL', 'LMNR', 'LMNX', 'LMPX', 'LMRK', 'LMRKN', 'LMRKO', 'LMRKP', 'LMST', 'LNDC', 'LNGR', 'LNT', 'LNTH', 'LOAC', 'LOACR', 'LOACU', 'LOACW', 'LOAN', 'LOB', 'LOCO', 'LOGC', 'LOGI', 'LOGM', 'LONE', 'LOOP', 'LOPE', 'LORL', 'LOVE', 'LPCN', 'LPLA', 'LPSN', 'LPTH', 'LPTX', 'LQDA', 'LQDT', 'LRCX', 'LRGE', 'LSACU', 'LSBK', 'LSCC', 'LSTR', 'LSXMA', 'LSXMB', 'LSXMK', 'LTBR', 'LTRPA', 'LTRPB', 'LTRX', 'LULU', 'LUNA', 'LVGO', 'LVHD', 'LWAY', 'LX', 'LXRX', 'LYFT', 'LYL', 'LYTS', 'MACK', 'MAGS', 'MANH', 'MANT', 'MAR', 'MARA', 'MARK', 'MARPS', 'MASI', 'MAT', 'MATW', 'MAYS', 'MBB', 'MBCN', 'MBII', 'MBIN', 'MBINO', 'MBINP', 'MBIO', 'MBNKP', 'MBOT', 'MBRX', 'MBSD', 'MBUU', 'MBWM', 'MCBC', 'MCBS', 'MCEF', 'MCEP', 'MCFT', 'MCHI', 'MCHP', 'MCHX', 'MCMJ', 'MCMJW', 'MCRB', 'MCRI', 'MDB', 'MDCA', 'MDGL', 'MDGS', 'MDIA', 'MDIV', 'MDJH', 'MDLZ', 'MDRR', 'MDRRP', 'MDRX', 'MDWD', 'MEDP', 'MEDS', 'MEET', 'MEIP', 'MELI', 'MEOH', 'MERC', 'MESA', 'MESO', 'METC', 'MFH', 'MFIN', 'MFINL', 'MFNC', 'MFSF', 'MGEE', 'MGEN', 'MGI', 'MGIC', 'MGLN', 'MGNX', 'MGPI', 'MGRC', 'MGTA', 'MGTX', 'MGYR', 'MHLD', 'MICT', 'MIDD', 'MIK', 'MILN', 'MIME', 'MIND', 'MINDP', 'MINI', 'MIRM', 'MIST', 'MITK', 'MITO', 'MJCO', 'MKD', 'MKGI', 'MKSI', 'MKTX', 'MLAB', 'MLCO', 'MLHR', 'MLND', 'MLNX', 'MLVF', 'MMAC', 'MMLP', 'MMSI', 'MMYT', 'MNCL', 'MNCLU', 'MNCLW', 'MNDO', 'MNKD', 'MNLO', 'MNOV', 'MNPR', 'MNRO', 'MNSB', 'MNST', 'MNTA', 'MNTX', 'MOBL', 'MOFG', 'MOGO', 'MOHO', 'MOMO', 'MOR', 'MORF', 'MORN', 'MOSY', 'MOTS', 'MOXC', 'MPAA', 'MPB', 'MPWR', 'MRAM', 'MRBK', 'MRCC', 'MRCCL', 'MRCY', 'MREO', 'MRIN', 'MRKR', 'MRLN', 'MRNA', 'MRNS', 'MRSN', 'MRTN', 'MRTX', 'MRUS', 'MRVL', 'MSBF', 'MSBI', 'MSEX', 'MSFT', 'MSON', 'MSTR', 'MSVB', 'MTBC', 'MTBCP', 'MTC', 'MTCH', 'MTEM', 'MTEX', 'MTLS', 'MTP', 'MTRX', 'MTSC', 'MTSI', 'MTSL', 'MU', 'MUDS', 'MUDSU', 'MUDSW', 'MVBF', 'MVIS', 'MWK', 'MXIM', 'MYFW', 'MYGN', 'MYL', 'MYOK', 'MYOS', 'MYRG', 'MYSZ', 'MYT', 'NAII', 'NAKD', 'NAOV', 'NATH', 'NATI', 'NATR', 'NAVI', 'NBACU', 'NBEV', 'NBIX', 'NBL', 'NBLX', 'NBN', 'NBRV', 'NBSE', 'NBTB', 'NCBS', 'NCMI', 'NCNA', 'NCSM', 'NCTY', 'NDAQ', 'NDLS', 'NDRA', 'NDRAW', 'NDSN', 'NEBU', 'NEBUU', 'NEBUW', 'NEO', 'NEOG', 'NEON', 'NEOS', 'NEPH', 'NEPT', 'NERV', 'NESR', 'NESRW', 'NETE', 'NEWA', 'NEWT', 'NEWTI', 'NEWTL', 'NEXT', 'NFBK', 'NFE', 'NFIN', 'NFINU', 'NFINW', 'NFLX', 'NFTY', 'NGHC', 'NGHCN', 'NGHCO', 'NGHCP', 'NGHCZ', 'NGM', 'NH', 'NHLD', 'NHLDW', 'NHTC', 'NICE', 'NICK', 'NIU', 'NK', 'NKSH', 'NKTR', 'NLNK', 'NLOK', 'NLTX', 'NMCI', 'NMIH', 'NMRD', 'NMRK', 'NNBR', 'NNDM', 'NODK', 'NOVN', 'NOVT', 'NPA', 'NPAUU', 'NPAWW', 'NRBO', 'NRC', 'NRIM', 'NSEC', 'NSIT', 'NSSC', 'NSTG', 'NSYS', 'NTAP', 'NTCT', 'NTEC', 'NTES', 'NTGN', 'NTGR', 'NTIC', 'NTLA', 'NTNX', 'NTRA', 'NTRP', 'NTRS', 'NTRSO', 'NTUS', 'NTWK', 'NUAN', 'NURO', 'NUROW', 'NUVA', 'NVAX', 'NVCN', 'NVCR', 'NVDA', 'NVEC', 'NVEE', 'NVFY', 'NVIV', 'NVMI', 'NVUS', 'NWBI', 'NWFL', 'NWGI', 'NWL', 'NWLI', 'NWPX', 'NWS', 'NWSA', 'NXGN', 'NXPI', 'NXST', 'NXTC', 'NXTD', 'NXTG', 'NYMT', 'NYMTM', 'NYMTN', 'NYMTO', 'NYMTP', 'NYMX', 'OAS', 'OBAS', 'OBCI', 'OBLN', 'OBNK', 'OBSV', 'OCC', 'OCCI', 'OCCIP', 'OCFC', 'OCGN', 'OCSI', 'OCSL', 'OCSLL', 'OCUL', 'ODFL', 'ODP', 'ODT', 'OESX', 'OFED', 'OFIX', 'OFLX', 'OFS', 'OFSSI', 'OFSSL', 'OFSSZ', 'OGI', 'OIIM', 'OKTA', 'OLD', 'OLED', 'OLLI', 'OMAB', 'OMCL', 'OMER', 'OMEX', 'OMP', 'ON', 'ONB', 'ONCS', 'ONCT', 'ONCY', 'ONEM', 'ONEQ', 'ONEW', 'ONTX', 'ONTXW', 'ONVO', 'OPB', 'OPBK', 'OPCH', 'OPES', 'OPESU', 'OPESW', 'OPGN', 'OPGNW', 'OPHC', 'OPI', 'OPINI', 'OPK', 'OPNT', 'OPOF', 'OPRA', 'OPRT', 'OPRX', 'OPTN', 'OPTT', 'ORBC', 'ORG', 'ORGO', 'ORGS', 'ORLY', 'ORMP', 'ORRF', 'ORSN', 'ORSNR', 'ORSNU', 'ORSNW', 'ORTX', 'OSBC', 'OSBCP', 'OSIS', 'OSMT', 'OSN', 'OSPN', 'OSS', 'OSTK', 'OSUR', 'OSW', 'OTEL', 'OTEX', 'OTIC', 'OTLK', 'OTLKW', 'OTTR', 'OTTW', 'OVBC', 'OVID', 'OVLY', 'OXBR', 'OXBRW', 'OXFD', 'OXLC', 'OXLCM', 'OXLCO', 'OXLCP', 'OXSQ', 'OXSQL', 'OXSQZ', 'OYST', 'OZK', 'PAAC', 'PAACR', 'PAACU', 'PAACW', 'PAAS', 'PACB', 'PACQ', 'PACQU', 'PACQW', 'PACW', 'PAE', 'PAEWW', 'PAHC', 'PANL', 'PASG', 'PATI', 'PATK', 'PAVM', 'PAVMW', 'PAVMZ', 'PAYS', 'PAYX', 'PBBI', 'PBCT', 'PBCTP', 'PBFS', 'PBHC', 'PBIP', 'PBPB', 'PBTS', 'PBYI', 'PCAR', 'PCB', 'PCH', 'PCOM', 'PCRX', 'PCSB', 'PCTI', 'PCTY', 'PCYG', 'PCYO', 'PDBC', 'PDCE', 'PDCO', 'PDD', 'PDEV', 'PDEX', 'PDFS', 'PDLB', 'PDLI', 'PDP', 'PDSB', 'PEBK', 'PEBO', 'PECK', 'PEGA', 'PEGI', 'PEIX', 'PENN', 'PEP', 'PERI', 'PESI', 'PETQ', 'PETS', 'PETZ', 'PEY', 'PEZ', 'PFBC', 'PFBI', 'PFF', 'PFG', 'PFHD', 'PFI', 'PFIE', 'PFIN', 'PFIS', 'PFLT', 'PFM

In [3]:
tickers = {}
for ticker in allTickers:
    tickers[ticker] = yf.Ticker(ticker)

### Below is an exploration of the package using Microsoft

In [6]:
msft = yf.Ticker("MSFT")
print(msft.info['sector'])
# json.loads(msft.info)

Technology

In [6]:
msft.balance_sheet

,2019-06-30,2018-06-30,2017-06-30,2016-06-30
Intangible Assets,7.750000e+09,8.053000e+09,1.010600e+10,3.733000e+09
Total Liab,1.842260e+11,1.761300e+11,1.626010e+11,1.214710e+11
Total Stockholder Equity,1.023300e+11,8.271800e+10,8.771100e+10,7.199700e+10
Other Current Liab,4.586000e+10,3.819500e+10,3.087900e+10,3.397200e+10
Total Assets,2.865560e+11,2.588480e+11,2.503120e+11,1.934680e+11
Common Stock,7.852000e+10,7.122300e+10,6.931500e+10,6.817800e+10
Other Current Assets,1.013300e+10,6.855000e+09,5.183000e+09,6.091000e+09
Retained Earnings,2.415000e+10,1.368200e+10,1.776900e+10,2.282000e+09
Other Liab,3.569900e+10,3.570700e+10,2.298600e+10,2.079600e+10
Good Will,4.202600e+10,3.568300e+10,3.512200e+10,1.787200e+10
Treasury Stock,-3.400000e+08,-2.187000e+09,6.270000e+08,1.537000e+09
Other Assets,1.472300e+10,7.442000e+09,6.076000e+09,3.409000e+09
Cash,1.135600e+10,1.194600e+10,7.663000e+09,6.510000e+09
Total Current Liabilities,6.942000e+10,5.848800e+10,5.574500e+10,5.935700e+10
Deferred Long Term Asset Charges,7.536000e+09,1.369000e+09,2.480000e+08,2.190000e+08
Short Long Term Debt,5.516000e+09,3.998000e+09,1.049000e+09,NaN
Other Stockholder Equity,-3.400000e+08,-2.187000e+09,6.270000e+08,1.537000e+09
Property Plant Equipment,4.385600e+10,3.614600e+10,3.028900e+10,1.835600e+10
Total Current Assets,1.755520e+11,1.696620e+11,1.626960e+11,1.396600e+11
Long Term Investments,2.649000e+09,1.862000e+09,6.023000e+09,1.043800e+10
Net Tangible Assets,5.255400e+10,3.898200e+10,4.248300e+10,5.039200e+10
Short Term Investments,1.224760e+11,1.217180e+11,1.252380e+11,1.065310e+11
Net Receivables,2.952400e+10,2.648100e+10,2.243100e+10,1.827700e+10
Long Term Debt,6.666200e+10,7.224200e+10,7.607300e+10,4.055700e+10
Inventory,2.063000e+09,2.662000e+09,2.181000e+09,2.251000e+09
Accounts Payable,9.382000e+09,8.617000e+09,7.390000e+09,6.898000e+09

In [7]:
dir(msft)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_balancesheet',
 '_base_url',
 '_calendar',
 '_cashflow',
 '_download_options',
 '_earnings',
 '_expirations',
 '_financials',
 '_fundamentals',
 '_get_fundamentals',
 '_history',
 '_info',
 '_institutional_holders',
 '_isin',
 '_major_holders',
 '_options2df',
 '_recommendations',
 '_scrape_url',
 '_sustainability',
 'actions',
 'balance_sheet',
 'balancesheet',
 'calendar',
 'cashflow',
 'dividends',
 'earnings',
 'financials',
 'get_actions',
 'get_balance_sheet',
 'get_balancesheet',
 'get_calendar',
 'get_cashflow',
 'get_dividends',
 'get_earnings',
 'get_financials',
 'get_info',
 'get_institutional_holders',
 'get_isin',
 'get_major_holders',
 'get_recommendations',
 'get_splits',
 'get_sustainability',
 'history',
 'info',
 'institutional_holders',
 'isin',
 'major_holders',
 'option_chain',
 'options',
 'quarterly_balance_sheet',
 'quarterly_balancesheet',
 'quarterly_cashflow',
 'quarterly_earnings',
 'quarterly_financials',
 'recommendations',
 'splits',
 'sustainability',
 'ticker']

In [23]:
msft.history(interval='1mo',period='6mo')

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2019-10-01,138.81,144.78,132.41,142.49,549523400.0,0.00,0
2019-11-01,143.38,151.57,142.10,150.46,392371800.0,0.00,0
2019-11-20,NaN,NaN,NaN,NaN,NaN,0.51,0
2019-12-01,151.40,159.12,146.25,157.27,450303300.0,0.00,0
2020-01-01,158.35,173.58,156.08,169.77,558530000.0,0.00,0
2020-02-01,169.97,190.18,151.59,161.57,887625300.0,0.00,0
2020-02-19,NaN,NaN,NaN,NaN,NaN,0.51,0
2020-03-01,165.31,175.00,138.58,139.06,598156700.0,0.00,0
2020-03-12,145.30,153.42,138.58,139.06,93226366.0,0.00,0

In [8]:
msft.get_cashflow()

,2019-06-30,2018-06-30,2017-06-30,2016-06-30
Investments,5.400000e+08,6.557000e+09,-1.251100e+10,-1.441700e+10
Change To Liabilities,4.694000e+09,7.070000e+09,3.901000e+09,2.653000e+09
Total Cashflows From Investing Activities,-1.577300e+10,-6.061000e+09,-4.678100e+10,-2.395000e+10
Net Borrowings,-4.000000e+09,-1.020100e+10,3.145900e+10,1.828300e+10
Total Cash From Financing Activities,-3.688700e+10,-3.359000e+10,8.408000e+09,-8.393000e+09
Change To Operating Activities,-1.542000e+09,-4.590000e+08,3.490000e+08,-2.907000e+09
Issuance Of Stock,1.142000e+09,1.002000e+09,7.720000e+08,6.680000e+08
Net Income,3.924000e+10,1.657100e+10,2.548900e+10,2.053900e+10
Change In Cash,-5.900000e+08,4.283000e+09,1.153000e+09,9.150000e+08
Repurchase Of Stock,-1.954300e+10,-1.072100e+10,-1.178800e+10,-1.596900e+10
Effect Of Exchange Rate,-1.150000e+08,5.000000e+07,1.900000e+07,-6.700000e+07
Total Cash From Operating Activities,5.218500e+10,4.388400e+10,3.950700e+10,3.332500e+10
Depreciation,1.160000e+10,9.900000e+09,7.800000e+09,5.878000e+09
Dividends Paid,-1.381100e+10,-1.269900e+10,-1.184500e+10,-1.100600e+10
Change To Inventory,5.970000e+08,-4.650000e+08,5.000000e+07,6.000000e+08
Change To Account Receivables,-2.812000e+09,-3.862000e+09,-1.216000e+09,5.620000e+08
Other Cashflows From Financing Activities,-6.750000e+08,-9.710000e+08,-1.900000e+08,-3.690000e+08
Change To Netincome,-2.521000e+09,-3.054000e+09,1.342000e+09,6.229000e+09
Capital Expenditures,-1.392500e+10,-1.163200e+10,-8.129000e+09,-8.343000e+09
Other Cashflows From Investing Activities,NaN,-9.800000e+07,-1.970000e+08,2.030000e+08

In [9]:
msft.recommendations

                          Firm        To Grade From Grade Action
Date
2012-07-20       Goldman Sachs         Neutral              main
2012-07-20  Griffin Securities             Buy              init
2012-08-20    Longbow Research             Buy              init
2012-09-12           Jefferies            Hold              init
2012-10-01         RBC Capital  Sector Perform              down
...                        ...             ...        ...    ...
2019-12-17       Deutsche Bank             Buy              main
2020-01-08      Morgan Stanley      Overweight              main
2020-01-09             Wedbush      Outperform              main
2020-01-09         Cowen & Co.      Outperform              main
2020-01-10           Jefferies             Buy              main

[226 rows x 4 columns]

In [24]:
msft.earnings

           Revenue     Earnings
Year
2016   91154000000  20539000000
2017   96571000000  25489000000
2018  110360000000  16571000000
2019  125843000000  39240000000

In [11]:
msft.history(period="max")

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
1986-03-13,0.06,0.07,0.06,0.06,1031788800,0.0,0.0
1986-03-14,0.06,0.07,0.06,0.06,308160000,0.0,0.0
1986-03-17,0.06,0.07,0.06,0.07,133171200,0.0,0.0
1986-03-18,0.07,0.07,0.06,0.06,67766400,0.0,0.0
1986-03-19,0.06,0.06,0.06,0.06,47894400,0.0,0.0
...,...,...,...,...,...,...,...
2020-03-06,162.61,163.11,156.00,161.57,72821100,0.0,0.0
2020-03-09,151.00,157.75,150.00,150.62,70419300,0.0,0.0
2020-03-10,158.16,161.03,152.58,160.92,65354400,0.0,0.0
2020-03-11,157.13,157.70,151.15,153.63,56371600,0.0,0.0
2020-03-12,145.30,153.47,138.58,139.06,92850800,0.0,0.0

In [12]:
msft.quarterly_balance_sheet

,2019-12-31,2019-09-30,2019-06-30,2019-03-31
Intangible Assets,7.126000e+09,7.508000e+09,7.750000e+09,8.103000e+09
Total Liab,1.726850e+11,1.728940e+11,1.842260e+11,1.684170e+11
Total Stockholder Equity,1.101090e+11,1.060610e+11,1.023300e+11,9.486400e+10
Other Current Liab,3.708100e+10,3.989600e+10,4.586000e+10,3.229500e+10
Total Assets,2.827940e+11,2.789550e+11,2.865560e+11,2.632810e+11
Common Stock,7.962500e+10,7.888200e+10,7.852000e+10,7.779100e+10
Other Current Assets,7.495000e+09,7.578000e+09,1.013300e+10,7.131000e+09
Retained Earnings,3.073900e+10,2.724000e+10,2.415000e+10,1.833800e+10
Other Liab,3.422500e+10,3.417800e+10,3.569900e+10,3.647100e+10
Good Will,4.224800e+10,4.211300e+10,4.202600e+10,4.186100e+10
Treasury Stock,-2.550000e+08,-6.100000e+07,-3.400000e+08,-1.265000e+09
Other Assets,1.463000e+10,1.445500e+10,1.472300e+10,1.025800e+10
Cash,8.864000e+09,1.311700e+10,1.135600e+10,1.121200e+10
Total Current Liabilities,5.964000e+10,5.811800e+10,6.942000e+10,5.386100e+10
Short Long Term Debt,6.247000e+09,3.017000e+09,5.516000e+09,6.515000e+09
Other Stockholder Equity,-2.550000e+08,-6.100000e+07,-3.400000e+08,-1.265000e+09
Property Plant Equipment,4.896100e+10,4.629900e+10,4.385600e+10,4.076900e+10
Total Current Assets,1.670740e+11,1.658960e+11,1.755520e+11,1.598870e+11
Long Term Investments,2.755000e+09,2.684000e+09,2.649000e+09,2.403000e+09
Net Tangible Assets,6.073500e+10,5.644000e+10,5.255400e+10,4.490000e+10
Short Term Investments,1.253670e+11,1.234920e+11,1.224760e+11,1.203240e+11
Net Receivables,2.352500e+10,1.908700e+10,2.952400e+10,1.926900e+10
Long Term Debt,6.336100e+10,6.647800e+10,6.666200e+10,6.658500e+10
Inventory,1.823000e+09,2.622000e+09,2.063000e+09,1.951000e+09
Accounts Payable,8.811000e+09,8.574000e+09,9.382000e+09,7.544000e+09
Deferred Long Term Asset Charges,NaN,NaN,7.536000e+09,NaN

In [13]:
msft.financials

,2019-06-30,2018-06-30,2017-06-30,2016-06-30
Research Development,1.6876e+10,1.4726e+10,1.3037e+10,1.1988e+10
Effect Of Accounting Charges,None,None,None,None
Income Before Tax,4.3688e+10,3.6474e+10,2.9901e+10,2.5639e+10
Minority Interest,None,None,None,None
Net Income,3.924e+10,1.6571e+10,2.5489e+10,2.0539e+10
Selling General Administrative,2.3098e+10,2.2223e+10,1.9942e+10,1.9198e+10
Gross Profit,8.2933e+10,7.2007e+10,6.231e+10,5.8374e+10
Ebit,4.2959e+10,3.5058e+10,2.9331e+10,2.7188e+10
Operating Income,4.2959e+10,3.5058e+10,2.9331e+10,2.7188e+10
Other Operating Expenses,None,None,None,None
Interest Expense,-2.686e+09,-2.733e+09,-2.222e+09,-1.243e+09
Extraordinary Items,None,None,None,None
Non Recurring,None,None,None,None
Other Items,None,None,None,None
Income Tax Expense,4.448e+09,1.9903e+10,4.412e+09,5.1e+09
Total Revenue,1.25843e+11,1.1036e+11,9.6571e+10,9.1154e+10
Total Operating Expenses,8.2884e+10,7.5302e+10,6.724e+10,6.3966e+10
Cost Of Revenue,4.291e+10,3.8353e+10,3.4261e+10,3.278e+10
Total Other Income Expense Net,7.29e+08,1.416e+09,5.7e+08,-1.549e+09
Discontinued Operations,None,None,None,None
Net Income From Continuing Ops,3.924e+10,1.6571e+10,2.5489e+10,2.0539e+10
Net Income Applicable To Common Shares,3.924e+10,1.6571e+10,2.5489e+10,2.0539e+10

In [14]:
help(msft.get_financials)

Help on method get_financials in module yfinance.base:

get_financials(proxy=None, as_dict=False, freq='yearly') method of yfinance.ticker.Ticker instance

In [15]:
msft.get_financials(freq='quarterly')

,2019-12-31,2019-09-30,2019-06-30,2019-03-31
Research Development,4.603e+09,4.565e+09,4.513e+09,4.316e+09
Effect Of Accounting Charges,None,None,None,None
Income Before Tax,1.4085e+10,1.2686e+10,1.2596e+10,1.0486e+10
Minority Interest,None,None,None,None
Net Income,1.1649e+10,1.0678e+10,1.3187e+10,8.809e+09
Selling General Administrative,6.054e+09,5.398e+09,6.387e+09,5.744e+09
Gross Profit,2.4548e+10,2.2649e+10,2.3305e+10,2.0401e+10
Ebit,1.3891e+10,1.2686e+10,1.2405e+10,1.0341e+10
Operating Income,1.3891e+10,1.2686e+10,1.2405e+10,1.0341e+10
Other Operating Expenses,None,None,None,None
Interest Expense,-6.55e+08,-6.37e+08,-6.69e+08,-6.71e+08
Extraordinary Items,None,None,None,None
Non Recurring,None,None,None,None
Other Items,None,None,None,None
Income Tax Expense,2.436e+09,2.008e+09,-5.91e+08,1.677e+09
Total Revenue,3.6906e+10,3.3055e+10,3.3717e+10,3.0571e+10
Total Operating Expenses,2.3015e+10,2.0369e+10,2.1312e+10,2.023e+10
Cost Of Revenue,1.2358e+10,1.0406e+10,1.0412e+10,1.017e+10
Total Other Income Expense Net,1.94e+08,0,1.91e+08,1.45e+08
Discontinued Operations,None,None,None,None
Net Income From Continuing Ops,1.1649e+10,1.0678e+10,1.3187e+10,8.809e+09
Net Income Applicable To Common Shares,1.1649e+10,1.0678e+10,1.3187e+10,8.809e+09

In [26]:
msft.get_earnings?

In [28]:
msft.get_earnings(freq="quarterly")

             Revenue     Earnings
Quarter
1Q2019   30571000000   8809000000
2Q2019   33717000000  13187000000
3Q2019   33055000000  10678000000
4Q2019   36906000000  11649000000